import { describe, expect, it, vi } from "vitest";
import { handleRouteRequest } from "../worker/index";

const body = { origin: { latitude: 35.6909, longitude: 139.6992 }, destination: { latitude: 35.6895, longitude: 139.6922 }, preferences: { maxContinuousWalkingMinutes: 10, requireToilet: true, avoidSteepSlopes: true, preferIndoorRest: false, avoidSteps: true } };
const ors = { features: [{ geometry: { coordinates: [[139.6992, 35.6909], [139.6922, 35.6895]] }, properties: { summary: { distance: 1000, duration: 720 }, segments: [], extras: {} } }] };
const apiRequest = (value: unknown = body, headers: Record<string, string> = {}) => new Request("https://example.test/api/routes", { method: "POST", headers: { "content-type": "application/json", ...headers }, body: JSON.stringify(value) });
const cache = () => { const entries = new Map<string, Response>(); return { match: vi.fn(async (request: Request) => entries.get(request.url)?.clone()), put: vi.fn(async (request: Request, response: Response) => { entries.set(request.url, response.clone()); }) }; };

describe("Worker routes API", () => {
  it("POSTとContent-Typeだけを受け付ける", async () => { expect((await handleRouteRequest(new Request("https://x/api/routes"), {})).status).toBe(405); expect((await handleRouteRequest(new Request("https://x/api/routes", { method: "POST", body: "{}" }), {})).status).toBe(400); });
  it("壊れたJSONと過大リクエストを拒否する", async () => { const broken = new Request("https://x/api/routes", { method: "POST", headers: { "content-type": "application/json" }, body: "{" }); expect((await handleRouteRequest(broken, {})).status).toBe(400); expect((await handleRouteRequest(apiRequest(body, { "content-length": "999999" }), {})).status).toBe(413); });
  it("APIキーなしでは安全な503を返す", async () => { const response = await handleRouteRequest(apiRequest(), {}); expect(response.status).toBe(503); expect(await response.text()).not.toContain("OPENROUTESERVICE_API_KEY"); });
  it("3候補を取得しキーをレスポンスやログへ含めない", async () => { const fetchImpl = vi.fn(async () => Response.json(ors)); const response = await handleRouteRequest(apiRequest(), { OPENROUTESERVICE_API_KEY: "secret-value" }, { fetchImpl: fetchImpl as typeof fetch, now: () => "now" }); const text = await response.text(); expect(response.status).toBe(200); expect(fetchImpl).toHaveBeenCalledTimes(3); expect(text).not.toContain("secret-value"); });
  it.each([[401, 502], [429, 503], [500, 502]])("外部API %iを安全な%iへ変換する", async (upstream, expected) => { const response = await handleRouteRequest(apiRequest(), { OPENROUTESERVICE_API_KEY: "secret" }, { fetchImpl: vi.fn(async () => new Response("raw secret error", { status: upstream })) as typeof fetch }); expect(response.status).toBe(expected); expect(await response.text()).not.toContain("raw secret error"); });
  it("タイムアウトを504へ変換する", async () => { const fetchImpl = vi.fn((_url: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError"))))); const response = await handleRouteRequest(apiRequest(), { OPENROUTESERVICE_API_KEY: "secret" }, { fetchImpl: fetchImpl as typeof fetch, timeoutMilliseconds: 1 }); expect(response.status).toBe(504); });
  it("同一要求ではキャッシュを利用する", async () => { const memory = cache(); const fetchImpl = vi.fn(async () => Response.json(ors)); const dependencies = { cache: memory, fetchImpl: fetchImpl as typeof fetch, now: () => "now" }; expect((await handleRouteRequest(apiRequest(), { OPENROUTESERVICE_API_KEY: "secret" }, dependencies)).status).toBe(200); expect((await handleRouteRequest(apiRequest(), { OPENROUTESERVICE_API_KEY: "secret" }, dependencies)).status).toBe(200); expect(fetchImpl).toHaveBeenCalledTimes(3); expect(memory.match).toHaveBeenCalledTimes(2); });
});
